default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: testing_development
  
test:
  <<: *default
  database: testing_test

production:
  <<: *default
  database: testing_production
  username: ubuntu
  password: ubuntu